#+property: header-args :tangle jmw.sty :noweb yes
* package header
:PROPERTIES:
:created:  2020-04-25 01:09:01 EDT
:END:
Credit inspirations.
#+BEGIN_SRC latex
% Much of this is copied from Evan Chen. 
#+END_SRC

#+BEGIN_SRC latex
\ProvidesPackage{jmwcommon}
\newif\ifjmwmdfthm\jmwmdfthmfalse
\newif\ifjmwcolorlinks\jmwcolorlinksfalse
\DeclareOption{sexy}{\jmwmdfthmtrue\jmwcolorlinkstrue}
\ProcessOptions\relax
#+END_SRC
* use packages
:PROPERTIES:
:created:  2020-04-25 01:09:24 EDT
:END:
=\align=, =\text=, =\DeclareMathOperator=.
#+BEGIN_SRC latex
\usepackage{amsmath}
#+END_SRC

More (though rarely used) math symbols. The list can be googled. 
#+BEGIN_SRC latex
\usepackage{amssymb}
#+END_SRC

Not entirely sure, but part of AMSLaTeX.
#+BEGIN_SRC latex
\usepackage{amsthm}
#+END_SRC

Script fonts. See [[https://www.stat.colostate.edu/~vollmer/pdfs/typesetting-script.pdf][here]]. Nike Sun likes these. 
#+BEGIN_SRC latex
\usepackage{mathrsfs} 
#+END_SRC

LaTeX's standard package for colors. =usenames= and co make more colors
available.
#+BEGIN_SRC latex
\usepackage[usenames,svgnames,dvipsnames]{xcolor}
  \definecolor{lightred}{rgb}{0.5,0,0}
#+END_SRC

Hyperlink support---make =\ref= clickable. 
#+BEGIN_SRC latex
\ifjmwcolorlinks
  \usepackage[colorlinks=true]{hyperref}
  \hypersetup{urlcolor=RubineRed,linkcolor=RoyalBlue,citecolor=ForestGreen}
\else
  \usepackage{hyperref}
\fi
#+END_SRC

=\includegraphics=.
#+BEGIN_SRC latex
\usepackage{graphicx}
#+END_SRC

Typeset nice SI units, like kg*m/s^2. [2020-05-22 Fri] not used often. 
#+BEGIN_SRC latex
\usepackage{siunitx}
#+END_SRC

Better double-struck characters. Suggested by Harry Yu. 
#+BEGIN_SRC latex
\usepackage{dsfont} % sexy double-struck chars
#+END_SRC
* macro
:PROPERTIES:
:created:  2020-04-25 01:10:37 EDT
:END:
Abbreviations. No semantics. 
#+BEGIN_SRC latex
\newcommand{\FF}{\ensuremath{\mathds{F}}}
\newcommand{\PP}{\ensuremath{\mathds{P}}}
\newcommand{\EE}{\ensuremath{\mathds{E}}}
\newcommand{\eps}{\ensuremath{\epsilon}}
\newcommand{\dt}{\ensuremath{\delta}}
\newcommand{\del}{\partial} 
\newcommand{\scrG}{\ensuremath{\mathscr{G}}} % for sigma algebras
\newcommand{\scrF}{\ensuremath{\mathscr{F}}} % for sigma algebras
\newcommand{\scrB}{\ensuremath{\mathscr{B}}} % for borel algebras
\newcommand{\cbrt}{\sqrt[3]} % "cube root"
\renewcommand{\phi}{\varphi}
\renewcommand{\d}[1]{\ensuremath{\mathrm{d}{#1}}}
#+END_SRC

Number systems. 
#+BEGIN_SRC latex
\newcommand{\NN}{\ensuremath{\mathds{N}}}
\newcommand{\ZZ}{\ensuremath{\mathds{Z}}}
\newcommand{\QQ}{\ensuremath{\mathds{Q}}}
\newcommand{\RR}{\ensuremath{\mathds{R}}}
\newcommand{\CC}{\ensuremath{\mathds{C}}} 
\newcommand{\HH}{\ensuremath{\mathds{H}}} 
#+END_SRC

Probability Distributions.
#+BEGIN_SRC latex
\newcommand{\Unif}{\ensuremath{\textsc{Unif}}} 
\newcommand{\Geom}{\ensuremath{\textsc{Geom}}} 
\newcommand{\Exp}{\ensuremath{\textsc{Exp}}} 
\newcommand{\Cauchy}{\ensuremath{\textsc{Cauchy}}}
\newcommand{\Pois}{\ensuremath{\textsc{Pois}}}
\newcommand{\Gauss}{\mathcal{N}}
#+END_SRC

Groups and representations. 
#+BEGIN_SRC latex
\DeclareMathOperator{\GL}{GL} 
\DeclareMathOperator{\SL}{SL} 
\DeclareMathOperator{\GO}{GO} 
\DeclareMathOperator{\SO}{SO} 
\DeclareMathOperator{\GU}{GU} 
\DeclareMathOperator{\SU}{SU} 
#+END_SRC

Big-O and co.
#+BEGIN_SRC latex
\newcommand{\BigO}{\mathcal{O}} 
\newcommand{\BigOm}{\Omega} 
#+END_SRC

Maps \RR to some significance space. 
#+BEGIN_SRC latex
\DeclareMathOperator{\fl}{fl} 
#+END_SRC

KL divergence.
#+BEGIN_SRC latex
\newcommand{\KL}[2]{\ensuremath{D_{KL}\left(#1, #2\right)}}
#+END_SRC

Equals sign that defines something.
#+BEGIN_SRC latex
\newcommand{\defeq}{\ensuremath{\stackrel{\mathrm{def}}{=}}} 
#+END_SRC

Insert an email address.
#+BEGIN_SRC latex
\newcommand{\mailto}[1]{\href{mailto:#1}{\texttt{#1}}}
#+END_SRC

Norm (normed vector spaces).
#+BEGIN_SRC latex
\newcommand{\norm}[1]{\ensuremath{\left\lVert #1\right\rVert}}
#+END_SRC

Absolute value of a complex number (or more generally, a quaternion).
#+BEGIN_SRC latex
\newcommand{\abs}[1]{\ensuremath{\left\lvert #1\right\rvert}}
#+END_SRC

Floor function. 
#+BEGIN_SRC latex
\newcommand{\floor}[1]{\ensuremath{\left\lfloor #1\right\rfloor}}
#+END_SRC

Sphere. \SS^n is a subspace of \RR^{n+1}
#+BEGIN_SRC latex
\renewcommand{\SS}{\ensuremath{\mathds{S}}} % sphere
#+END_SRC

Misc stuff from 18.675. 
#+BEGIN_SRC latex
\renewcommand{\Pr}[1]{\PP[#1]}
\newcommand{\ind}[1]{\ensuremath{\mathbf{1}_{#1}}} % indicator func
\newcommand{\Ev}{\EE} % expected value
\newcommand{\probto}{\xrightarrow{p}}
\newcommand{\asto}{\xrightarrow{a.s.}}
\newcommand{\distto}{\xrightarrow{d}}
\newcommand{\Law}[1]{\ensuremath{\mathcal{L}_{#1}}} 
#+END_SRC

Cardinality of a set. 
#+BEGIN_SRC latex
\newcommand{\card}[1]{\ensuremath{\abs{#1}}} 
#+END_SRC

Inner product.
#+BEGIN_SRC latex
\newcommand{\ip}[2]{\ensuremath{\left\langle #1, #2\right\rangle}} 
#+END_SRC

#+BEGIN_SRC latex
\DeclareMathOperator{\Tr}{Tr} % "Trace"
\DeclareMathOperator{\D}{D} % Jacobian
#+END_SRC

Bolded vector.
#+BEGIN_SRC latex
\newcommand{\bvec}[1]{\ensuremath{\mathbf{#1}}} 
#+END_SRC
** other
:PROPERTIES:
:created:  2020-05-22 04:37:13 EDT
:END:
Not satisfied with calling signature. Hope a better solution exists.
#+BEGIN_SRC latex
\renewcommand\th{^{\text{\normalfont{th}}}} % Harry likes this
\newcommand{\degrees}{^\circ} % "degrees"
#+END_SRC
* style
:PROPERTIES:
:created:  2020-04-25 01:11:50 EDT
:END:
This is probably better in a document class
#+BEGIN_SRC latex
\setlength{\parskip}{0.5\baselineskip}
\setlength{\parindent}{0pt}
#+END_SRC
* thm
:PROPERTIES:
:created:  2020-04-25 01:12:50 EDT
:END:
#+BEGIN_SRC latex
\usepackage{thmtools}

\ifjmwmdfthm
  <<mdf-thm>>
\else
  \newtheorem{theorem}{Theorem}[section]
  \newtheorem{lemma}[theorem]{Lemma}
  \newtheorem{definition}[theorem]{Definition}
\fi
#+END_SRC
** mdf-thm
:PROPERTIES:
:created:  2020-05-24 18:07:43 EDT
:header-args: :noweb-ref mdf-thm :tangle no
:END:
Main framing package.
#+BEGIN_SRC latex
\usepackage[framemethod=TikZ]{mdframed}
#+END_SRC

Evan's boxes and theorem styles. 
#+BEGIN_SRC latex
\mdfdefinestyle{mdfbluebox}{%
  roundcorner=10pt,
  linewidth=1pt,
  skipabove=12pt,
  innerbottommargin=9pt,
  skipbelow=2pt,
  linecolor=blue,
  nobreak=true,
  backgroundcolor=TealBlue!5,
}
\declaretheoremstyle[
  headfont=\sffamily\bfseries\color{MidnightBlue},
  mdframed={style=mdfbluebox},
  headpunct={\\[3pt]},
  postheadspace={0pt}
]{thmbluebox}

\mdfdefinestyle{mdfgreenbox}{%
  roundcorner=10pt,
  linewidth=1pt,
  skipabove=12pt,
  innerbottommargin=9pt,
  skipbelow=2pt,
  linecolor=green,
  nobreak=true,
  backgroundcolor=LimeGreen!5,
}
\declaretheoremstyle[
  headfont=\sffamily\bfseries\color{OliveGreen},
  mdframed={style=mdfgreenbox},
  headpunct={\\[3pt]},
  postheadspace={0pt}
]{thmgreenbox}

\mdfdefinestyle{mdfredbox}{%
  linewidth=0.5pt,
  skipabove=12pt,
  frametitleaboveskip=5pt,
  frametitlebelowskip=0pt,
  skipbelow=2pt,
  frametitlefont=\bfseries,
  innertopmargin=4pt,
  innerbottommargin=8pt,
  nobreak=true,
  backgroundcolor=Salmon!5,
  linecolor=RawSienna,
}
\declaretheoremstyle[
  headfont=\bfseries\color{RawSienna},
  mdframed={style=mdfredbox},
  headpunct={\\[3pt]},
  postheadspace={0pt},
]{thmredbox}

% numbered
\declaretheorem[style=thmbluebox,name=Theorem]{theorem}
\declaretheorem[style=thmbluebox,name=Lemma,sibling=theorem]{lemma}
\declaretheorem[style=thmbluebox,name=Proposition,sibling=theorem]{proposition}
\declaretheorem[style=thmgreenbox,name=Definition,sibling=theorem]{definition}
\declaretheorem[style=thmredbox,name=Argument]{argument}

% no number
\declaretheorem[style=thmbluebox,name=Theorem,numbered=no]{theorem*}
\declaretheorem[style=thmbluebox,name=Proposition,numbered=no]{proposition*}
\declaretheorem[style=thmbluebox,name=Corollary,numbered=no]{corollary*}  
#+END_SRC
* other
:PROPERTIES:
:created:  2020-04-25 01:13:55 EDT
:END:
#+BEGIN_SRC latex
\@ifundefined{KOMAClassName}
{}
{
  \setkomafont{author}{\Large\scshape}
  \setkomafont{date}{\Large\normalsize}
}
#+END_SRC

pgfplots expressions. 
#+BEGIN_SRC latex
\newcommand{\pgfcauchypdf}[2]{(#2)/(pi*((#2)^2+(x-(#1))^2))}
#+END_SRC

kora. 
#+BEGIN_SRC latex
\newcommand{\kora}{%
(\raisebox{0.5em}{\rotatebox{-45}{)}}$^{\circ}{\scriptscriptstyle\Box}^{\circ}$)\raisebox{0.5em}{\rotatebox{-45}{)}}\rotatebox{90}{)}\raisebox{0.5ex}{$\bot$}$\mkern-3.5mu-\mkern-3.5mu$\raisebox{0.5ex}{$\bot$}
}
#+END_SRC
